### ISSUE TITLE
SystemD Log Shipping

### ISSUE THREAD

**Issue by clone1018** [Glimesh/ops#19]
Currently all systemd logging happens on the local servers. In order to debug we have to remote into the specific server and use journalctl to figure out what happened.

It would be nice to ship this to a central location for easy debugging / monitoring.

**Comment by LukeHandle** [comment]
Hi, I'll be looking into this.

Initial thoughts are Loki + Promtail. That will be each node pushing the logs back to the monitor node. Initially a shared key and basic auth protecting the HTTPS endpoint, (could potentially advance to certs, or encapsulate in something else down the line).

Use of Loki means we can directly integrate with Grafana and have a single dashboarding tool.

**Comment by LukeHandle** [comment]
Another one pending #15 and #25. I can do some further testing, but they will block.

**Comment by LukeHandle** [comment]
First pass is at #27 for the monitoring server. Still need to overcome auth, but it'll be good to get some running info in the meantime.
