### ISSUE TITLE
Add LetsEncrypt to Grafana 

### ISSUE THREAD

**Issue by clone1018** [Glimesh/ops#23]
Currently it is being served over http on a non-standard port.

**Comment by LukeHandle** [comment]
I propose `grafana.<node>` and `prometheus.<node>` ? 


At some point, a better solution to the auth will be needed as well. OAuth2 type things are perfect IMHO. You would want to ensure it's decoupled from Glimesh auth (in case there are issues there). Using GitHub as an auth provider seems sensible.

**Comment by LukeHandle** [comment]
Pending #15 and #25, I can add the HTTPS in. Grafana natively support GH auth which would be an easy short term win as well.
